=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/Forecast-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-Forecast-2",
  "description": "A document used to forecast sales or orders.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-Forecast-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
          },
          "minItems": 1
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
          },
          "minItems": 1
        }
      ]
    },
    "VersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/VersionID"
    },
    "BasedOnConsensusIndicator": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/BasedOnConsensusIndicator"
    },
    "ForecastPurposeCode": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ForecastPurposeCode"
    },
    "ForecastPeriod": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          },
          "minItems": 1
        }
      ]
    },
    "SenderParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "SellerSupplierParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "ForecastLine": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/ForecastLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/ForecastLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "ForecastPurposeCode",
    "ForecastPeriod",
    "SenderParty",
    "ReceiverParty",
    "ForecastLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Forecast. Details"
}

=== kduvekot/ubl-json/NSxlB/NSxlB/NSxlB/NSxlB/json/examples/UBL-Forecast-2.1-Example.json
{
  "UBLEntity": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-Forecast-2",
  "UBLVersionID": "2.1",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-1-cpfr-forecast-draft",
  "ID": "OF758494",
  "UUID": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4",
  "IssueDate": "2010-01-01",
  "IssueTime": "12:00:01.000Z",
  "Note": "sample",
  "BasedOnConsensusIndicator": true,
  "ForecastPurposeCode": "ORDER_FORECAST",
  "ForecastPeriod": {
    "StartDate": "2010-02-01",
    "EndDate": "2010-05-26"
  },
  "SenderParty": {
    "PartyIdentification": {
      "ID": "6903148000007"
    },
    "PartyName": {
      "Name": "Consortial"
    },
    "PostalAddress": {
      "StreetName": "Busy Street",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Farthing",
      "PostalZone": "AA99 1BB",
      "CountrySubentity": "Heremouthshire",
      "AddressLine": {
        "Line": "The Roundabout"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Farthing Purchasing Consortium",
      "CompanyID": "175 269 2355",
      "ExemptionReason": "N/A",
      "TaxScheme": {
        "ID": "VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mrs Bouquet",
      "Telephone": "0158 1233714",
      "Telefax": "0158 1233856",
      "ElectronicMail": "bouquet@fpconsortial.co.uk"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "2203148000007"
    },
    "PartyName": {
      "Name": "IYT Corporation"
    },
    "PostalAddress": {
      "StreetName": "Avon Way",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Bridgtow",
      "PostalZone": "ZZ99 1ZZ",
      "CountrySubentity": "Avon",
      "AddressLine": {
        "Line": "3rd Floor, Room 5"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Bridgtow District Council",
      "CompanyID": "12356478",
      "ExemptionReason": "Local Authority",
      "TaxScheme": {
        "ID": "UK VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mr Fred Churchill",
      "Telephone": "0127 2653214",
      "Telefax": "0127 2653215",
      "ElectronicMail": "fred@iytcorporation.gov.uk"
    }
  },
  "BuyerCustomerParty": {
    "Party": {
      "PartyIdentification": {
        "ID": "0012345000359"
      }
    }
  },
  "SellerSupplierParty": {
    "Party": {
      "PartyIdentification": {
        "ID": "0012345000058"
      }
    }
  },
  "ForecastLine": {
    "ID": "forecastLineID",
    "ForecastTypeCode": "TOTAL",
    "ForecastPeriod": {
      "StartDate": "2010-02-01",
      "EndDate": "2010-05-26"
    },
    "SalesItem": {
      "Quantity": {
        "value": 20,
        "unitCode": "KGM"
      },
      "Item": {
        "Description": "Acme beeswax",
        "Name": "beeswax",
        "BuyersItemIdentification": {
          "ID": "6578489"
        },
        "SellersItemIdentification": {
          "ID": "17589683"
        },
        "StandardItemIdentification": {
          "ID": "00123450000584"
        }
      }
    }
  }
}
