=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/SelfBilledCreditNote-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:SelfBilledCreditNote-2",
  "description": "A credit note created by the debtor in a self billing arrangement with a creditor.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:SelfBilledCreditNote-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "DueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DueDate"
    },
    "TaxPointDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TaxPointDate"
    },
    "CreditNoteTypeCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CreditNoteTypeCode"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "DocumentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentCurrencyCode"
    },
    "TaxCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TaxCurrencyCode"
    },
    "PricingCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PricingCurrencyCode"
    },
    "PaymentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PaymentCurrencyCode"
    },
    "PaymentAlternativeCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/PaymentAlternativeCurrencyCode"
    },
    "AccountingCostCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/AccountingCostCode"
    },
    "AccountingCost": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/AccountingCost"
    },
    "LineCountNumeric": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/LineCountNumeric"
    },
    "DefaultLanguageCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DefaultLanguageCode"
    },
    "InvoicePeriod": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
          }
        }
      ]
    },
    "DiscrepancyResponse": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ResponseType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ResponseType"
          }
        }
      ]
    },
    "OrderReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/OrderReferenceType"
    },
    "BillingReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BillingReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BillingReferenceType"
          }
        }
      ]
    },
    "DespatchDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "DeliveryNoteDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "WorkReportDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ReceiptDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ContractDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "StatementDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "OriginatorDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "ProjectReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ProjectReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ProjectReferenceType"
          }
        }
      ]
    },
    "BuyerAssignedReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BuyerAssignedReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/BuyerAssignedReferenceType"
          }
        }
      ]
    },
    "PurchaseReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PurchaseReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PurchaseReferenceType"
          }
        }
      ]
    },
    "Annotation": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AnnotationType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AnnotationType"
          }
        }
      ]
    },
    "AccountingCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "AccountingSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "PayeeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "SellerSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "TaxRepresentativeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "Delivery": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryType"
          }
        }
      ]
    },
    "DeliveryTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DeliveryTermsType"
          }
        }
      ]
    },
    "PaymentMeans": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
          }
        }
      ]
    },
    "PaymentTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
          }
        }
      ]
    },
    "AllowanceCharge": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
          }
        }
      ]
    },
    "TaxExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PricingExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PaymentExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "PaymentAlternativeExchangeRate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ExchangeRateType"
    },
    "TaxTotal": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
          }
        }
      ]
    },
    "WithholdingTaxTotal": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
          }
        }
      ]
    },
    "LegalMonetaryTotal": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/MonetaryTotalType"
    },
    "CollectionCreditNoteLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
          }
        }
      ]
    },
    "CreditNoteLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CreditNoteLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "AccountingCustomerParty",
    "AccountingSupplierParty",
    "LegalMonetaryTotal",
    "CreditNoteLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Self Billed Credit Note. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-SelfBilledCreditNote-2.1-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:SelfBilledCreditNote-2",
  "UBLVersionID": "2.1",
  "ID": "TOSL108",
  "IssueDate": "2009-12-15",
  "Note": {
    "value": "Ordered in our booth at the convention.",
    "languageID": "en"
  },
  "DocumentCurrencyCode": {
    "value": "EUR",
    "listID": "6:ISO 4217 Alpha"
  },
  "AccountingCost": "Project cost code 123",
  "InvoicePeriod": {
    "StartDate": "2009-11-01",
    "EndDate": "2009-11-30"
  },
  "OrderReference": {
    "ID": "123"
  },
  "ContractDocumentReference": {
    "ID": "Contract321",
    "DocumentType": "Framework agreement"
  },
  "AdditionalDocumentReference": [
    {
      "ID": "Doc1",
      "DocumentType": "Timesheet",
      "Attachment": {
        "ExternalReference": {
          "URI": "http://www.suppliersite.eu/sheet001.html"
        }
      }
    },
    {
      "ID": "Doc2",
      "DocumentType": "Drawing",
      "Attachment": {
        "EmbeddedDocumentBinaryObject": {
          "value": "UjBsR09EbGhjZ0dTQUxNQUFBUUNBRU1tQ1p0dU1GUXhEUzhi",
          "mimeCode": "application/pdf"
        }
      }
    }
  ],
  "AccountingCustomerParty": {
    "Party": {
      "PartyIdentification": {
        "ID": {
          "value": "345KS5324",
          "schemeID": "ZZZ"
        }
      },
      "PartyName": {
        "Name": "Buyercompany ltd"
      },
      "PostalAddress": {
        "ID": {
          "value": "1238764941386",
          "schemeID": "9:GLN"
        },
        "Postbox": "123",
        "StreetName": "Anystreet",
        "AdditionalStreetName": "Back door",
        "BuildingNumber": "8",
        "Department": "Accounting department",
        "CityName": "Anytown",
        "PostalZone": "101",
        "CountrySubentity": "RegionB",
        "Country": {
          "IdentificationCode": {
            "value": "BE",
            "listID": "6:ISO3166-1"
          }
        }
      },
      "PartyTaxScheme": {
        "CompanyID": {
          "value": "BE54321",
          "schemeID": "ZZZ:BEVAT"
        },
        "TaxScheme": {
          "ID": {
            "value": "VAT",
            "schemeID": "6:UN/ECE 5153"
          }
        }
      },
      "PartyLegalEntity": {
        "RegistrationName": "The buyercompany inc.",
        "CompanyID": {
          "value": "5645342123",
          "schemeID": "ZZZ:ZZZ"
        },
        "RegistrationAddress": {
          "CityName": "Mainplace",
          "CountrySubentity": "RegionB",
          "Country": {
            "IdentificationCode": "BE"
          }
        }
      },
      "Contact": {
        "Telephone": "5121230",
        "Telefax": "5121231",
        "ElectronicMail": "john@buyercompany.eu"
      },
      "Person": {
        "FirstName": "John",
        "FamilyName": "X",
        "MiddleName": "Doe",
        "JobTitle": "Purchasing manager"
      }
    }
  },
  "AccountingSupplierParty": {
    "Party": {
      "PartyIdentification": {
        "ID": {
          "value": "Supp123",
          "schemeID": "ZZZ"
        }
      },
      "PartyName": {
        "Name": "Salescompany ltd."
      },
      "PostalAddress": {
        "ID": {
          "value": "1231412341324",
          "schemeID": "9:GLN"
        },
        "Postbox": "5467",
        "StreetName": "Main street",
        "AdditionalStreetName": "Suite 123",
        "BuildingNumber": "1",
        "Department": "Revenue department",
        "CityName": "Big city",
        "PostalZone": "54321",
        "CountrySubentityCode": "RegionA",
        "Country": {
          "IdentificationCode": {
            "value": "DK",
            "listID": "6:ISO3166-1"
          }
        }
      },
      "PartyTaxScheme": {
        "CompanyID": {
          "value": "DK12345",
          "schemeID": "ZZZ:DKVAT"
        },
        "TaxScheme": {
          "ID": {
            "value": "VAT",
            "schemeID": "6:UN/ECE 5153"
          }
        }
      },
      "PartyLegalEntity": {
        "RegistrationName": "The Sellercompany Incorporated",
        "CompanyID": {
          "value": "5402697509",
          "schemeID": "ZZZ:CVR"
        },
        "RegistrationAddress": {
          "CityName": "Big city",
          "CountrySubentity": "RegionA",
          "Country": {
            "IdentificationCode": "DK"
          }
        }
      },
      "Contact": {
        "Telephone": "4621230",
        "Telefax": "4621231",
        "ElectronicMail": "antonio@salescompany.dk"
      },
      "Person": {
        "FirstName": "Antonio",
        "FamilyName": "M",
        "MiddleName": "Salemacher",
        "JobTitle": "Sales manager"
      }
    }
  },
  "PayeeParty": {
    "PartyIdentification": {
      "ID": {
        "value": "098740918237",
        "schemeID": "9:GLN"
      }
    },
    "PartyName": {
      "Name": "Ebeneser Scrooge Inc."
    },
    "PartyLegalEntity": {
      "CompanyID": {
        "value": "6411982340",
        "schemeID": "ZZZ:UK:CH"
      }
    }
  },
  "AllowanceCharge": [
    {
      "ChargeIndicator": true,
      "AllowanceChargeReason": "Packing cost",
      "Amount": {
        "value": 100,
        "currencyID": "EUR"
      }
    },
    {
      "ChargeIndicator": false,
      "AllowanceChargeReason": "Promotion discount",
      "Amount": {
        "value": 100,
        "currencyID": "EUR"
      }
    }
  ],
  "TaxTotal": {
    "TaxAmount": {
      "value": 292.2,
      "currencyID": "EUR"
    },
    "TaxSubtotal": [
      {
        "TaxableAmount": {
          "value": 1460.5,
          "currencyID": "EUR"
        },
        "TaxAmount": {
          "value": 292.1,
          "currencyID": "EUR"
        },
        "TaxCategory": {
          "ID": {
            "value": "S",
            "schemeID": "6:UN/ECE 5305"
          },
          "Percent": 20,
          "TaxScheme": {
            "ID": {
              "value": "VAT",
              "schemeID": "6:UN/ECE 5153"
            }
          }
        }
      },
      {
        "TaxableAmount": {
          "value": 1,
          "currencyID": "EUR"
        },
        "TaxAmount": {
          "value": 0.1,
          "currencyID": "EUR"
        },
        "TaxCategory": {
          "ID": {
            "value": "AA",
            "schemeID": "6:UN/ECE 5305"
          },
          "Percent": 10,
          "TaxScheme": {
            "ID": {
              "value": "VAT",
              "schemeID": "6:UN/ECE 5153"
            }
          }
        }
      },
      {
        "TaxableAmount": {
          "value": -25,
          "currencyID": "EUR"
        },
        "TaxAmount": {
          "value": 0,
          "currencyID": "EUR"
        },
        "TaxCategory": {
          "ID": {
            "value": "E",
            "schemeID": "6:UN/ECE 5305"
          },
          "Percent": 0,
          "TaxExemptionReasonCode": {
            "value": "AAM",
            "listID": "ZZZ:CWA 15577"
          },
          "TaxExemptionReason": "Exempt New Means of Transport",
          "TaxScheme": {
            "ID": {
              "value": "VAT",
              "schemeID": "6:UN/ECE 5153"
            }
          }
        }
      }
    ]
  },
  "LegalMonetaryTotal": {
    "LineExtensionAmount": {
      "value": 1436.5,
      "currencyID": "EUR"
    },
    "TaxExclusiveAmount": {
      "value": 1436.5,
      "currencyID": "EUR"
    },
    "TaxInclusiveAmount": {
      "value": 1729,
      "currencyID": "EUR"
    },
    "AllowanceTotalAmount": {
      "value": 100,
      "currencyID": "EUR"
    },
    "ChargeTotalAmount": {
      "value": 100,
      "currencyID": "EUR"
    },
    "PrepaidAmount": {
      "value": 1000,
      "currencyID": "EUR"
    },
    "PayableRoundingAmount": {
      "value": 0.3,
      "currencyID": "EUR"
    },
    "PayableAmount": {
      "value": 729,
      "currencyID": "EUR"
    }
  },
  "CreditNoteLine": [
    {
      "ID": "1",
      "Note": "Scratch on box",
      "CreditedQuantity": {
        "value": 1,
        "unitCode": "C62"
      },
      "LineExtensionAmount": {
        "value": 1273,
        "currencyID": "EUR"
      },
      "AccountingCost": "BookingCode001",
      "TaxTotal": {
        "TaxAmount": {
          "value": 254.6,
          "currencyID": "EUR"
        }
      },
      "Item": {
        "Description": {
          "value": "Processor: Intel Core 2 Duo SU9400 LV (1.4GHz). RAM:\n\t\t\t\t3MB. Screen 1440x900",
          "languageID": "EN"
        },
        "Name": "Labtop computer",
        "SellersItemIdentification": {
          "ID": "JB007"
        },
        "StandardItemIdentification": {
          "ID": {
            "value": "1234567890124",
            "schemeID": "9:GTIN"
          }
        },
        "CommodityClassification": [
          {
            "ItemClassificationCode": {
              "value": "12344321",
              "listID": "113:UNSPSC"
            }
          },
          {
            "ItemClassificationCode": {
              "value": "65434568",
              "listID": "2:CPV"
            }
          }
        ],
        "ClassifiedTaxCategory": {
          "ID": {
            "value": "S",
            "schemeID": "6:UN/ECE 5305"
          },
          "Percent": 20,
          "TaxScheme": {
            "ID": {
              "value": "VAT",
              "schemeID": "6:UN/ECE 5153"
            }
          }
        },
        "AdditionalItemProperty": {
          "Name": "Color",
          "Value": "black"
        }
      },
      "Price": {
        "PriceAmount": {
          "value": 1273,
          "currencyID": "EUR"
        },
        "BaseQuantity": {
          "value": 1,
          "unitCode": "C62"
        },
        "AllowanceCharge": {
          "ChargeIndicator": false,
          "AllowanceChargeReason": "Contract",
          "MultiplierFactorNumeric": 0.15,
          "Amount": {
            "value": 225,
            "currencyID": "EUR"
          },
          "BaseAmount": {
            "value": 1500,
            "currencyID": "EUR"
          }
        }
      }
    },
    {
      "ID": "2",
