=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/Statement-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:Statement-2",
  "description": "A document used to report the status of orders, billing, and payment. This document is a statement of account, not a summary invoice.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:Statement-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "DocumentCurrencyCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentCurrencyCode"
    },
    "TotalDebitAmount": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TotalDebitAmount"
    },
    "TotalCreditAmount": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TotalCreditAmount"
    },
    "TotalBalanceAmount": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TotalBalanceAmount"
    },
    "LineCountNumeric": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/LineCountNumeric"
    },
    "StatementTypeCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/StatementTypeCode"
    },
    "StatementPeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "AccountingSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "AccountingCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "SellerSupplierParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "OriginatorCustomerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "BeneficiaryParty": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
          }
        }
      ]
    },
    "PayeeParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "PaymentMeans": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentMeansType"
          }
        }
      ]
    },
    "PaymentTerms": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
          }
        }
      ]
    },
    "AllowanceCharge": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/AllowanceChargeType"
          }
        }
      ]
    },
    "TaxTotal": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TaxTotalType"
          }
        }
      ]
    },
    "StatementLine": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/StatementLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/StatementLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "DocumentCurrencyCode",
    "AccountingSupplierParty",
    "AccountingCustomerParty",
    "StatementLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Statement. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-Statement-2.0-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:Statement-2",
  "UBLVersionID": "2.0",
  "CustomizationID": "urn:oasis:names:specification:ubl:xpath:Statement-2.0:sbs-1.0-draft",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-statement-notification-draft",
  "ID": "JUL2005-07758990",
  "UUID": "normalizedString",
  "IssueDate": "2005-08-02",
  "Note": "please present invoice if this credit amount cannot be taken against a forthcoming payment",
  "DocumentCurrencyCode": "GBP",
  "TotalDebitAmount": {
    "value": 0.0,
    "currencyID": "GBP"
  },
  "TotalCreditAmount": {
    "value": 107.5,
    "currencyID": "GBP"
  },
  "TotalBalanceAmount": {
    "value": -107.5,
    "currencyID": "GBP"
  },
  "StatementPeriod": {
    "StartDate": "2005-07-01",
    "EndDate": "2005-07-31",
    "Description": "July"
  },
  "AccountingSupplierParty": {
    "CustomerAssignedAccountID": "CO001",
    "Party": {
      "PartyName": {
        "Name": "Consortial"
      },
      "PostalAddress": {
        "StreetName": "Busy Street",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Farthing",
        "PostalZone": "AA99 1BB",
        "CountrySubentity": "Heremouthshire",
        "AddressLine": {
          "Line": "The Roundabout"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Farthing Purchasing Consortium",
        "CompanyID": "175 269 2355",
        "ExemptionReason": "N/A",
        "TaxScheme": {
          "ID": "VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mrs Bouquet",
        "Telephone": "0158 1233714",
        "Telefax": "0158 1233856",
        "ElectronicMail": "bouquet@fpconsortial.co.uk"
      }
    }
  },
  "AccountingCustomerParty": {
    "CustomerAssignedAccountID": "XFB01",
    "SupplierAssignedAccountID": "GT00978567",
    "Party": {
      "PartyName": {
        "Name": "IYT Corporation"
      },
      "PostalAddress": {
        "StreetName": "Avon Way",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Bridgtow",
        "PostalZone": "ZZ99 1ZZ",
        "CountrySubentity": "Avon",
        "AddressLine": {
          "Line": "3rd Floor, Room 5"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Bridgtow District Council",
        "CompanyID": "12356478",
        "ExemptionReason": "Local Authority",
        "TaxScheme": {
          "ID": "UK VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mr Fred Churchill",
        "Telephone": "0127 2653214",
        "Telefax": "0127 2653215",
        "ElectronicMail": "fred@iytcorporation.gov.uk"
      }
    }
  },
  "PayeeParty": {
    "PartyName": {
      "Name": "Consortial"
    },
    "PostalAddress": {
      "StreetName": "Busy Street",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Farthing",
      "PostalZone": "AA99 1BB",
      "CountrySubentity": "Heremouthshire",
      "AddressLine": {
        "Line": "The Roundabout"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Farthing Purchasing Consortium",
      "CompanyID": "175 269 2355",
      "ExemptionReason": "N/A",
      "TaxScheme": {
        "ID": "VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mrs Bouquet",
      "Telephone": "0158 1233714",
      "Telefax": "0158 1233856",
      "ElectronicMail": "bouquet@fpconsortial.co.uk"
    }
  },
  "PaymentMeans": {
    "PaymentMeansCode": "20",
    "PaymentDueDate": "2005-07-21",
    "PayeeFinancialAccount": {
      "ID": "12345678",
      "Name": "Farthing Purchasing Consortium",
      "AccountTypeCode": "Current",
      "CurrencyCode": "GBP",
      "FinancialInstitutionBranch": {
        "ID": "10-26-58",
        "Name": "Open Bank Ltd, Bridgstow Branch",
        "FinancialInstitution": {
          "ID": "10-26-58",
          "Name": "Open Bank Ltd",
          "Address": {
            "StreetName": "City Road",
            "BuildingName": "Banking House",
            "BuildingNumber": "12",
            "CityName": "London",
            "PostalZone": "AQ1 6TH",
            "CountrySubentity": "London",
            "AddressLine": {
              "Line": "5th Floor"
            },
            "Country": {
              "IdentificationCode": "GB"
            }
          }
        },
        "Address": {
          "StreetName": "Busy Street",
          "BuildingName": "The Mall",
          "BuildingNumber": "152",
          "CityName": "Farthing",
          "PostalZone": "AA99 1BB",
          "CountrySubentity": "Heremouthshire",
          "AddressLine": {
            "Line": "West Wing"
          },
          "Country": {
            "IdentificationCode": "GB"
          }
        }
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    }
  },
  "PaymentTerms": {
    "Note": "Payment due immediately"
  },
  "StatementLine": {
    "ID": "normalizedString",
    "Note": "String",
    "BalanceBroughtForwardIndicator": false,
    "DebitLineAmount": {
      "value": 0.0,
      "currencyID": "GBP"
    },
    "CreditLineAmount": {
      "value": 107.5,
      "currencyID": "GBP"
    },
    "BalanceAmount": {
      "value": -107.5,
      "currencyID": "GBP"
    },
    "OriginatorCustomerParty": {
      "Party": {
        "PartyName": {
          "Name": "The Terminus"
        },
        "PostalAddress": {
          "StreetName": "Avon Way",
          "BuildingName": "Thereabouts",
          "BuildingNumber": "56A",
          "CityName": "Bridgtow",
          "PostalZone": "ZZ99 1ZZ",
          "CountrySubentity": "Avon",
          "AddressLine": {
            "Line": "3rd Floor, Room 5"
          },
          "Country": {
            "IdentificationCode": "GB"
          }
        },
        "PartyTaxScheme": {
          "RegistrationName": "Bridgtow District Council",
          "CompanyID": "12356478",
          "ExemptionReason": "Local Authority",
          "TaxScheme": {
            "ID": "UK VAT",
            "TaxTypeCode": "VAT"
          }
        },
        "Contact": {
          "Name": "S Massiah",
          "Telephone": "0127 98876545",
          "Telefax": "0127 98876546",
          "ElectronicMail": "smassiah@the-email.co.uk"
        }
      }
    },
    "BillingReference": {
      "CreditNoteDocumentReference": {
        "ID": "CN758494",
        "UUID": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4",
        "IssueDate": "2005-06-25"
      }
    }
  }
}
