=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/TransportServiceDescriptionRequest-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescriptionRequest-2",
  "description": "A document requesting a Transport Service Description, sent from a party with a transport demand (transport user) to a party providing transport services (transport service provider).",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescriptionRequest-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "ServiceInformationPreferenceCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ServiceInformationPreferenceCode"
    },
    "SenderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportServiceProviderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportationService": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "IssueTime",
    "TransportationService"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Transport Service Description Request. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-TransportServiceDescriptionRequest-2.1-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescriptionRequest-2",
  "UBLVersionID": "2.1",
  "ID": "TSD_REQ_1",
  "IssueDate": "2011-09-12",
  "IssueTime": "11:01:10+01:00",
  "SenderParty": {
    "PartyIdentification": {
      "ID": "4058673827000"
    },
    "PartyName": {
      "Name": "Consignor"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+8687878763",
      "ElectronicMail": "SomeName@consignor.cn"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "TransportationService": {
    "TransportServiceCode": "3",
    "TransportEquipment": [
      {
        "ID": "1",
        "TransportEquipmentTypeCode": "CN",
        "MeasurementDimension": [
          {
            "AttributeID": "Length",
            "Measure": {
              "value": 6.1,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Height",
            "Measure": {
              "value": 2.6,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Width",
            "Measure": {
              "value": 2.44,
              "unitCode": "MTR"
            }
          }
        ]
      },
      {
        "ID": "1",
        "TransportEquipmentTypeCode": "CN",
        "MeasurementDimension": [
          {
            "AttributeID": "Length",
            "Measure": {
              "value": 6.1,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Height",
            "Measure": {
              "value": 2.6,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Width",
            "Measure": {
              "value": 2.44,
              "unitCode": "MTR"
            }
          }
        ]
      }
    ],
    "ShipmentStage": {
      "ID": "1",
      "RequestedDepartureTransportEvent": {
        "Location": {
          "Address": {
            "ID": "DEHAM",
            "StreetName": "Neuer Wandrahm 4",
            "CityName": "Hamburg",
            "Country": {
              "IdentificationCode": "DE"
            }
          }
        },
        "Period": {
          "StartDate": "2011-10-03",
          "EndDate": "2011-10-03"
        }
      },
      "RequestedArrivalTransportEvent": {
        "Location": {
          "Address": {
            "StreetName": "Grosse strasse 34",
            "CityName": "Nurnberg",
            "Country": {
              "IdentificationCode": "DE"
            }
          }
        },
        "Period": {
          "StartDate": "2011-10-06",
          "EndDate": "2011-10-06"
        }
      }
    }
  }
}
