=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/TransportExecutionPlanRequest-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:TransportExecutionPlanRequest-2",
  "description": "A document sent by a transport user to request a transport service from a transport service provider.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:TransportExecutionPlanRequest-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "VersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/VersionID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "DocumentStatusCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentStatusCode"
    },
    "DocumentStatusReasonCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentStatusReasonCode"
    },
    "DocumentStatusReasonDescription": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentStatusReasonDescription"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/DocumentStatusReasonDescription"
          }
        }
      ]
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "TransportUserRemarks": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TransportUserRemarks"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/TransportUserRemarks"
          }
        }
      ]
    },
    "SenderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportUserParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportServiceProviderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "BillToParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportExecutionPlanDocumentReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "TransportServiceDescriptionDocumentReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          }
        }
      ]
    },
    "TransportContract": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ContractType"
    },
    "TransportServiceProviderResponseDeadlinePeriod": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
          }
        }
      ]
    },
    "MainTransportationService": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
    },
    "AdditionalTransportationService": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
          }
        }
      ]
    },
    "ServiceStartTimePeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "ServiceEndTimePeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "FromLocation": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/LocationType"
    },
    "ToLocation": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/LocationType"
    },
    "AtLocation": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/LocationType"
    },
    "TransportExecutionTerms": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportExecutionTermsType"
    },
    "Consignment": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ConsignmentType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/ConsignmentType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "TransportServiceProviderParty",
    "Consignment"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Transport Execution Plan Request. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-TransportExecutionPlanRequest-2.1-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:TransportExecutionPlanRequest-2",
  "UBLVersionID": "2.1",
  "ID": "TEPR_1",
  "VersionID": "1",
  "IssueDate": "2011-09-13",
  "IssueTime": "10:00:10+01:00",
  "DocumentStatusCode": "NotConfirmed",
  "SenderParty": {
    "PartyIdentification": {
      "ID": "4058673827000"
    },
    "PartyName": {
      "Name": "Consignor"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+8687878763",
      "ElectronicMail": "SomeName@consignor.cn"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "TransportUserParty": {
    "PartyIdentification": {
      "ID": "4058673827000"
    },
    "PartyName": {
      "Name": "Consignor"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+8687878763",
      "ElectronicMail": "SomeName@consignor.cn"
    }
  },
  "TransportServiceProviderParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "TransportServiceDescriptionDocumentReference": {
    "ID": "2"
  },
  "TransportContract": {
    "Note": "Framework Agreement",
    "ContractDocumentReference": {
      "ID": "TC101",
      "IssueDate": "2010-01-01",
      "DocumentTypeCode": "315",
      "DocumentType": "Contract",
      "DocumentDescription": "Framework Agreement between Consignor and NECOSS"
    }
  },
  "TransportServiceProviderResponseDeadlinePeriod": {
    "EndDate": "2011-09-13",
    "EndTime": "11:00:10+01:00"
  },
  "MainTransportationService": {
    "TransportServiceCode": "3",
    "TransportationServiceDescription": "Transport from Hamburg to Nurnberg"
  },
  "ServiceEndTimePeriod": {
    "EndDate": "2011-10-06",
    "EndTime": "16:00:10+01:00"
  },
  "FromLocation": {
    "LocationTypeCode": "13",
    "Address": {
      "ID": "DEHAM",
      "StreetName": "Neuer Wandrahm 4",
      "CityName": "Hamburg",
      "PostalZone": "29400",
      "Country": {
        "IdentificationCode": "DE"
      }
    }
  },
  "ToLocation": {
    "LocationTypeCode": "7",
    "Address": {
      "StreetName": "Grosse strasse 34",
      "CityName": "Nurnberg",
      "PostalZone": "28400",
      "Country": {
        "IdentificationCode": "DE"
      }
    }
  },
  "TransportExecutionTerms": {
    "DeliveryTerms": {
      "ID": "EXW",
      "DeliveryLocation": {
        "Address": {
          "CityName": "Hamburg"
        }
      }
    },
    "NotificationRequirement": [
      {
        "NotificationTypeCode": "TIME_SCHEDULE_DEVIATIONS",
        "NotifyParty": [
          {
            "PartyName": {
              "Name": "Consignee"
            },
            "Contact": {
              "ElectronicMail": "someName@consignee.de"
            }
          },
          {
            "PartyName": {
              "Name": "Consignor"
            },
            "Contact": {
              "ElectronicMail": "someName@consignor.cn"
            }
          }
        ]
      },
      {
        "NotificationTypeCode": "ITEM_CONDITION_DEVIATIONS",
        "PostEventNotificationDurationMeasure": {
          "value": 10,
          "unitCode": "MIN"
        },
        "NotifyParty": [
          {
            "PartyName": {
              "Name": "Consignee"
            },
            "Contact": {
              "ElectronicMail": "someName@consignee.de"
            }
          },
          {
            "PartyName": {
              "Name": "Consignor"
            },
            "Contact": {
              "ElectronicMail": "someName@consignor.cn"
            }
          }
        ]
      }
    ]
  },
  "Consignment": {
    "ID": "CON_1",
    "GrossWeightMeasure": {
      "value": 50000,
      "unitCode": "KGM"
    },
    "NetWeightMeasure": {
      "value": 3000,
      "unitCode": "KGM"
    },
    "GrossVolumeMeasure": {
      "value": 78,
      "unitCode": "MTQ"
    },
    "LoadingLengthMeasure": {
      "value": 12,
      "unitCode": "MTR"
    },
    "HazardousRiskIndicator": false,
    "TotalTransportHandlingUnitQuantity": 2,
    "ConsolidatedShipment": [
      {
        "ID": "GSIN_1"
      },
      {
        "ID": "GSIN_2"
      }
    ],
    "RequestedPickupTransportEvent": {
      "Location": {
        "Address": {
          "ID": "DEHAM",
          "StreetName": "Neuer Wandrahm 4",
          "CityName": "Hamburg",
          "PostalZone": "29400",
          "Country": {
            "IdentificationCode": "DE"
          }
        }
      },
      "Period": {
        "StartDate": "2011-10-03",
        "StartTime": "09:30:10+01:00",
        "EndDate": "2011-10-03",
        "EndTime": "12:30:10+01:00"
      }
    },
    "RequestedDeliveryTransportEvent": {
      "Location": {
        "Address": {
          "StreetName": "Grosse strasse 34",
          "CityName": "Nurnberg",
          "PostalZone": "28400",
          "Country": {
            "IdentificationCode": "DE"
          }
        }
      },
      "Period": {
        "StartDate": "2011-10-06",
        "StartTime": "12:30:10+01:00",
        "EndDate": "2011-10-06",
        "EndTime": "15:30:10+01:00"
      }
    },
    "ConsigneeParty": {
      "PartyIdentification": {
        "ID": "4058673827123"
      },
      "PartyName": {
        "Name": "Consignee"
      },
      "Contact": {
        "Name": "SomeName",
        "Telephone": "+4987878763",
        "ElectronicMail": "SomeName@consignee.de"
      }
    },
    "ConsignorParty": {
      "PartyIdentification": {
        "ID": "4058673827000"
      },
      "PartyName": {
        "Name": "Consignor"
      },
      "PostalAddress": {
        "ID": "4058673827000"
      },
      "Contact": {
        "Name": "SomeName",
        "Telephone": "+8676576456",
        "ElectronicMail": "SomeName@consignor.cn"
      }
    },
    "OriginalDepartureCountry": {
      "IdentificationCode": "CN"
    },
    "FinalDestinationCountry": {
      "IdentificationCode": "DE"
    },
    "TransportHandlingUnit": [
      {
        "ID": "CON_THU_1",
        "TransportHandlingUnitTypeCode": "4",
        "HazardousRiskIndicator": false,
        "TotalGoodsItemQuantity": 500,
        "TotalPackageQuantity": 10,
        "ShippingMarks": "General Cargo",
        "TransportEquipment": {
          "ID": "CON_TE_1",
          "TransportEquipmentTypeCode": "CN",
          "FullnessIndicationCode": "1",
          "ReturnabilityIndicator": true,
          "RefrigeratedIndicator": false,
          "Description": "SomeDescription",
          "GrossWeightMeasure": {
            "value": 25000,
            "unitCode": "KGM"
          },
          "GrossVolumeMeasure": {
            "value": 39,
            "unitCode": "MTQ"
          },
          "PowerIndicator": false,
          "MeasurementDimension": [
            {
              "AttributeID": "Length",
              "Measure": {
                "value": 6.1,
                "unitCode": "MTR"
              }
            },
            {
              "AttributeID": "Height",
              "Measure": {
                "value": 2.6,
                "unitCode": "MTR"
              }
            },
            {
              "AttributeID": "Width",
              "Measure": {
                "value": 2.44,
                "unitCode": "MTR"
              }
            }
          ],
          "Package": {
            "ID": "CON_P_1",
            "Quantity": 10,
            "PackagingTypeCode": "PL",
            "GoodsItem": {
              "Item": {
                "CommodityClassification": {
                  "CargoTypeCode": "12"
                }
              }
            }
          }
        }
      },
      {
        "ID": "CON_THU_2",
        "TransportHandlingUnitTypeCode": "4",
        "HazardousRiskIndicator": false,
        "TotalGoodsItemQuantity": 500,
        "TotalPackageQuantity": 10,
        "ShippingMarks": "General Cargo",
        "TransportEquipment": {
          "ID": "CON_TE_2",
          "TransportEquipmentTypeCode": "CN",
          "FullnessIndicationCode": "1",
          "ReturnabilityIndicator": true,
          "RefrigeratedIndicator": false,
          "Description": "SomeDescription",
          "GrossWeightMeasure": {
            "value": 25000,
            "unitCode": "KGM"
          },
          "GrossVolumeMeasure": {
            "value": 39,
            "unitCode": "MTQ"
          },
          "PowerIndicator": false,
          "MeasurementDimension": [
            {
              "AttributeID": "Length",
              "Measure": {
                "value": 6.1,
                "unitCode": "MTR"
              }
            },
            {
              "AttributeID": "Height",
              "Measure": {
                "value": 2.6,
                "unitCode": "MTR"
              }
            },
            {
              "AttributeID": "Width",
              "Measure": {
                "value": 2.44,
                "unitCode": "MTR"
              }
            }
          ],
          "Package": {
            "ID": "CON_P_2",
            "Quantity": 10,
            "PackagingTypeCode": "PL",
            "GoodsItem": {
              "Item": {
                "CommodityClassification": {
                  "CargoTypeCode": "12"
                }
              }
            }
          }
        }
      }
    ]
  }
}
