=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/TransportProgressStatus-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:TransportProgressStatus-2",
  "description": "A document sent from a Transportation Network Manager to a Transport Service Provider giving the status of the whereabouts and schedule of the transport means involved in a transport service.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:TransportProgressStatus-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
          }
        }
      ]
    },
    "StatusAvailableIndicator": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/StatusAvailableIndicator"
    },
    "SenderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "SourceIssuerParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportProgressStatusRequestDocumentReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "TransportMeans": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportMeansType"
    },
    "TransportSchedule": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportScheduleType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportScheduleType"
          }
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "IssueTime",
    "TransportMeans"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Transport Progress Status. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-TransportProgressStatus-2.1-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:TransportProgressStatus-2",
  "UBLVersionID": "2.1",
  "ID": "TPSR_1",
  "IssueDate": "2011-10-03",
  "IssueTime": "14:30:10+01:00",
  "StatusAvailableIndicator": true,
  "SenderParty": {
    "PartyIdentification": {
      "ID": "4058673821325"
    },
    "PartyName": {
      "Name": "ARRIVA"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557888",
      "ElectronicMail": "SomeName@arriva.de"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "SourceIssuerParty": {
    "PartyIdentification": {
      "ID": "4058673821325"
    },
    "PartyName": {
      "Name": "ARRIVA"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557888",
      "ElectronicMail": "SomeName@arriva.de"
    }
  },
  "TransportProgressStatusRequestDocumentReference": {
    "ID": "TPS_1"
  },
  "TransportMeans": {
    "JourneyID": "RHamBrem",
    "RegistrationNationalityID": "DE",
    "TransportMeansTypeCode": "230",
    "RailTransport": {
      "TrainID": "RID01235"
    }
  },
  "TransportSchedule": {
    "SequenceNumeric": 1,
    "ReliabilityPercent": 80,
    "StatusLocation": {
      "LocationTypeCode": "13",
      "Address": {
        "ID": "4568763527610",
        "StreetName": "Ludwig-Erhard-Str. 15",
        "CityName": "Bremen",
        "Country": {
          "IdentificationCode": "DE"
        }
      }
    },
    "EstimatedArrivalTransportEvent": {
      "Period": {
        "StartDate": "2011-10-03",
        "StartTime": "18:30:10+01:00",
        "EndDate": "2011-10-03",
        "EndTime": "18:35:10+01:00"
      }
    }
  }
}
