=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/UBL-RemittanceAdvice-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-RemittanceAdvice-2",
  "description": "A document that specifies details of an actual payment.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-RemittanceAdvice-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "UBLVersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
          },
          "minItems": 1
        }
      ]
    },
    "DocumentCurrencyCode": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/DocumentCurrencyCode"
    },
    "TotalDebitAmount": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/TotalDebitAmount"
    },
    "TotalCreditAmount": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/TotalCreditAmount"
    },
    "TotalPaymentAmount": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/TotalPaymentAmount"
    },
    "PaymentOrderReference": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/PaymentOrderReference"
    },
    "PayerReference": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/PayerReference"
    },
    "InvoicingPartyReference": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/InvoicingPartyReference"
    },
    "LineCountNumeric": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/LineCountNumeric"
    },
    "InvoicePeriod": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PeriodType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PeriodType"
          },
          "minItems": 1
        }
      ]
    },
    "BillingReference": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/BillingReferenceType"
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          },
          "minItems": 1
        }
      ]
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
          },
          "minItems": 1
        }
      ]
    },
    "AccountingCustomerParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "AccountingSupplierParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "PayeeParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "PaymentMeans": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PaymentMeansType"
    },
    "TaxTotal": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/TaxTotalType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/TaxTotalType"
          },
          "minItems": 1
        }
      ]
    },
    "RemittanceAdviceLine": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/RemittanceAdviceLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/RemittanceAdviceLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "AccountingCustomerParty",
    "AccountingSupplierParty",
    "RemittanceAdviceLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Remittance Advice. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-RemittanceAdvice-2.0-Example.json
{
  "UBLEntity": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-RemittanceAdvice-2",
  "UBLVersionID": "2.0",
  "CustomizationID": "urn:oasis:names:specification:ubl:xpath:RemittanceAdvice-2.0:sbs-1.0-draft",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-sbs-remittance-advice-notification-draft",
  "ID": "6577884",
  "UUID": "84E081CE-F9D1-94C5-40F9-94C5FF9D1AC3",
  "IssueDate": "2005-06-22",
  "Note": "dummy as sample",
  "TotalDebitAmount": {
    "value": 107.5,
    "currencyID": "GBP"
  },
  "TotalCreditAmount": {
    "value": 0.0,
    "currencyID": "GBP"
  },
  "TotalPaymentAmount": {
    "value": 107.5,
    "currencyID": "GBP"
  },
  "InvoicePeriod": {
    "StartDate": "2005-06-01",
    "EndDate": "2005-07-01"
  },
  "AccountingCustomerParty": {
    "CustomerAssignedAccountID": "XFB01",
    "SupplierAssignedAccountID": "GT00978567",
    "Party": {
      "PartyName": {
        "Name": "IYT Corporation"
      },
      "PostalAddress": {
        "StreetName": "Avon Way",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Bridgtow",
        "PostalZone": "ZZ99 1ZZ",
        "CountrySubentity": "Avon",
        "AddressLine": {
          "Line": "3rd Floor, Room 5"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Bridgtow District Council",
        "CompanyID": "12356478",
        "ExemptionReason": "Local Authority",
        "TaxScheme": {
          "ID": "UK VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mr Fred Churchill",
        "Telephone": "0127 2653214",
        "Telefax": "0127 2653215",
        "ElectronicMail": "fred@iytcorporation.gov.uk"
      }
    }
  },
  "AccountingSupplierParty": {
    "CustomerAssignedAccountID": "CO001",
    "Party": {
      "PartyName": {
        "Name": "Consortial"
      },
      "PostalAddress": {
        "StreetName": "Busy Street",
        "BuildingName": "Thereabouts",
        "BuildingNumber": "56A",
        "CityName": "Farthing",
        "PostalZone": "AA99 1BB",
        "CountrySubentity": "Heremouthshire",
        "AddressLine": {
          "Line": "The Roundabout"
        },
        "Country": {
          "IdentificationCode": "GB"
        }
      },
      "PartyTaxScheme": {
        "RegistrationName": "Farthing Purchasing Consortium",
        "CompanyID": "175 269 2355",
        "ExemptionReason": "N/A",
        "TaxScheme": {
          "ID": "VAT",
          "TaxTypeCode": "VAT"
        }
      },
      "Contact": {
        "Name": "Mrs Bouquet",
        "Telephone": "0158 1233714",
        "Telefax": "0158 1233856",
        "ElectronicMail": "bouquet@fpconsortial.co.uk"
      }
    }
  },
  "PayeeParty": {
    "PartyName": {
      "Name": "Consortial"
    },
    "PostalAddress": {
      "StreetName": "Busy Street",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Farthing",
      "PostalZone": "AA99 1BB",
      "CountrySubentity": "Heremouthshire",
      "AddressLine": {
        "Line": "The Roundabout"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Farthing Purchasing Consortium",
      "CompanyID": "175 269 2355",
      "ExemptionReason": "N/A",
      "TaxScheme": {
        "ID": "VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mrs Bouquet",
      "Telephone": "0158 1233714",
      "Telefax": "0158 1233856",
      "ElectronicMail": "bouquet@fpconsortial.co.uk"
    }
  },
  "PaymentMeans": {
    "PaymentMeansCode": "20",
    "PaymentDueDate": "2005-07-21",
    "PayeeFinancialAccount": {
      "ID": "12345678",
      "Name": "Farthing Purchasing Consortium",
      "AccountTypeCode": "Current",
      "CurrencyCode": "GBP",
      "FinancialInstitutionBranch": {
        "ID": "10-26-58",
        "Name": "Open Bank Ltd, Bridgstow Branch",
        "FinancialInstitution": {
          "ID": "10-26-58",
          "Name": "Open Bank Ltd",
          "Address": {
            "StreetName": "City Road",
            "BuildingName": "Banking House",
            "BuildingNumber": "12",
            "CityName": "London",
            "PostalZone": "AQ1 6TH",
            "CountrySubentity": "London",
            "AddressLine": {
              "Line": "5th Floor"
            },
            "Country": {
              "IdentificationCode": "GB"
            }
          }
        },
        "Address": {
          "StreetName": "Busy Street",
          "BuildingName": "The Mall",
          "BuildingNumber": "152",
          "CityName": "Farthing",
          "PostalZone": "AA99 1BB",
          "CountrySubentity": "Heremouthshire",
          "AddressLine": {
            "Line": "West Wing"
          },
          "Country": {
            "IdentificationCode": "GB"
          }
        }
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    }
  },
  "RemittanceAdviceLine": {
    "ID": "1",
    "Note": "please note that local offices will close for recess for the next three weeks - please send their invoices to central offices for that time",
    "DebitLineAmount": {
      "value": 107.5,
      "currencyID": "GBP"
    },
    "CreditLineAmount": {
      "value": 0.0,
      "currencyID": "GBP"
    },
    "BalanceAmount": {
      "value": 107.5,
      "currencyID": "GBP"
    },
    "OriginatorCustomerParty": {
      "Party": {
        "PartyName": {
          "Name": "The Terminus"
        },
        "PostalAddress": {
          "StreetName": "Avon Way",
          "BuildingName": "Thereabouts",
          "BuildingNumber": "56A",
          "CityName": "Bridgtow",
          "PostalZone": "ZZ99 1ZZ",
          "CountrySubentity": "Avon",
          "AddressLine": {
            "Line": "3rd Floor, Room 5"
          },
          "Country": {
            "IdentificationCode": "GB"
          }
        },
        "PartyTaxScheme": {
          "RegistrationName": "Bridgtow District Council",
          "CompanyID": "12356478",
          "ExemptionReason": "Local Authority",
          "TaxScheme": {
            "ID": "UK VAT",
            "TaxTypeCode": "VAT"
          }
        },
        "Contact": {
          "Name": "S Massiah",
          "Telephone": "0127 98876545",
          "Telefax": "0127 98876546",
          "ElectronicMail": "smassiah@the-email.co.uk"
        }
      }
    },
    "BillingReference": {
      "InvoiceDocumentReference": {
        "ID": "A00095678",
        "UUID": "849FBBCE-E081-40B4-906C-94C5FF9D1AC3",
        "IssueDate": "2005-06-21"
      }
    }
  }
}
