=== kduvekot/ubl-json/gHfrj/json/schemas/maindoc/UBL-ProofOfReexportationReminder-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ProofOfReexportationReminder-2",
  "description": "A reminder that a requested Proof of Reexportation is pending.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ProofOfReexportationReminder-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "UBLVersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueTime"
    },
    "ProcedureCode": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProcedureCode"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
          },
          "minItems": 1
        }
      ]
    },
    "VersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/VersionID"
    },
    "GoodsItemPassportID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/GoodsItemPassportID"
    },
    "ProofOfReexportationRequestDocumentReference": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "ImportingGuarantorParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ExportingGuarantorParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ImportingCustomsParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "IssuerEndorsement": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/EndorsementType"
    },
    "PaymentTerms": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PaymentTermsType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PaymentTermsType"
          },
          "minItems": 1
        }
      ]
    },
    "GoodsItemPassportCounterfoil": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/GoodsItemPassportCounterfoilType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/GoodsItemPassportCounterfoilType"
          },
          "minItems": 1
        }
      ]
    },
    "AdditionalDocumentReference": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          },
          "minItems": 1
        }
      ]
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "ProcedureCode",
    "ProofOfReexportationRequestDocumentReference",
    "ImportingGuarantorParty",
    "ExportingGuarantorParty",
    "GoodsItemPassportCounterfoil"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Proof Of Reexportation Reminder. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-ProofOfReexportationReminder-2.3-Example.json
{
  "UBLEntity": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ProofOfReexportationReminder-2",
  "ID": "A2344",
  "IssueDate": "2019-06-21",
  "ProcedureCode": "A-letter",
  "ProofOfReexportationRequestDocumentReference": {
    "ID": "A2344"
  },
  "ImportingGuarantorParty": {
    "PartyName": {
      "Name": "Deutscher Industrie- und Handelskammertag e.V."
    },
    "PostalAddress": {
      "StreetName": "Breite Straße",
      "BuildingNumber": "29",
      "CityName": "Berlin",
      "PostalZone": "10178",
      "Country": {
        "IdentificationCode": "DE"
      }
    },
    "PartyLegalEntity": {
      "CompanyID": "DE122125278"
    }
  },
  "ExportingGuarantorParty": {
    "PartyName": {
      "Name": "Dansk Erhverv"
    },
    "PostalAddress": {
      "StreetName": "Slotsholmsgade",
      "BuildingNumber": "1",
      "CityName": "København K",
      "PostalZone": "1216",
      "Country": {
        "IdentificationCode": "DK"
      }
    },
    "PartyLegalEntity": {
      "CompanyID": "DK43232010"
    }
  },
  "ImportingCustomsParty": {
    "PartyName": {
      "Name": "Zollamt"
    },
    "PostalAddress": {
      "StreetName": "Tollbrettkoppel",
      "BuildingNumber": "8",
      "CityName": "Heiligenhafen",
      "PostalZone": "23774",
      "Country": {
        "IdentificationCode": "DE"
      }
    }
  },
  "GoodsItemPassportCounterfoil": {
    "ID": "645634567",
    "GoodsItemPassportID": "ata01661",
    "VoucherDocumentReference": {
      "ID": "23445567"
    }
  }
}
