=== kduvekot/ubl-json/NSxlB/NSxlB/json/schemas/maindoc/UBL-ExceptionCriteria-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ExceptionCriteria-2",
  "description": "A document used to specify the thresholds for forecast variance, product activity, and performance history beyond which exceptions will be triggered.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ExceptionCriteria-2",
      "description": "Identifies the JSON schema governing this instance."
    },
    "UBLExtensions": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "UBLVersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/ID"
    },
    "UUID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/Note"
          },
          "minItems": 1
        }
      ]
    },
    "VersionID": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonBasicComponents-2#/$defs/VersionID"
    },
    "ValidityPeriod": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "DocumentReference": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/DocumentReferenceType"
          },
          "minItems": 1
        }
      ]
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SignatureType"
          },
          "minItems": 1
        }
      ]
    },
    "SenderParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/PartyType"
    },
    "BuyerCustomerParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/CustomerPartyType"
    },
    "SellerSupplierParty": {
      "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/SupplierPartyType"
    },
    "ExceptionCriteriaLine": {
      "oneOf": [
        {
          "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/ExceptionCriteriaLineType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "https://docs.oasis-open.org/ubl/2/json/schemas/CommonAggregateComponents-2#/$defs/ExceptionCriteriaLineType"
          },
          "minItems": 1
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID",
    "IssueDate",
    "ValidityPeriod",
    "SenderParty",
    "ReceiverParty",
    "ExceptionCriteriaLine"
  ],
  "additionalProperties": false,
  "minProperties": 1,
  "title": "Exception Criteria. Details"
}

=== kduvekot/ubl-json/NSxlB/NSxlB/NSxlB/NSxlB/NSxlB/NSxlB/json/examples/UBL-ExceptionCriteria-2.1-Example.json
{
  "UBLEntity": "https://docs.oasis-open.org/ubl/2/json/schemas/UBL-ExceptionCriteria-2",
  "UBLVersionID": "2.1",
  "CustomizationID": "urn:oasis:names:specification:ubl:xpath:ExceptionCriteria-2.1:1.0-draft",
  "ProfileID": "bpid:urn:oasis:names:draft:bpss:ubl-2-cpfr-exception-criteria-draft",
  "ID": "EC758494",
  "UUID": "349ABBAE-DF9D-40B4-849F-94C5FF9D1AF4",
  "IssueDate": "2009-12-25",
  "Note": "sample",
  "ValidityPeriod": {
    "StartDate": "2010-03-28",
    "EndDate": "2010-08-29"
  },
  "SenderParty": {
    "PartyIdentification": {
      "ID": "6903148000007"
    },
    "PartyName": {
      "Name": "Consortial"
    },
    "PostalAddress": {
      "StreetName": "Busy Street",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Farthing",
      "PostalZone": "AA99 1BB",
      "CountrySubentity": "Heremouthshire",
      "AddressLine": {
        "Line": "The Roundabout"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Farthing Purchasing Consortium",
      "CompanyID": "175 269 2355",
      "ExemptionReason": "N/A",
      "TaxScheme": {
        "ID": "VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mrs Bouquet",
      "Telephone": "0158 1233714",
      "Telefax": "0158 1233856",
      "ElectronicMail": "bouquet@fpconsortial.co.uk"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "2203148000007"
    },
    "PartyName": {
      "Name": "IYT Corporation"
    },
    "PostalAddress": {
      "StreetName": "Avon Way",
      "BuildingName": "Thereabouts",
      "BuildingNumber": "56A",
      "CityName": "Bridgtow",
      "PostalZone": "ZZ99 1ZZ",
      "CountrySubentity": "Avon",
      "AddressLine": {
        "Line": "3rd Floor, Room 5"
      },
      "Country": {
        "IdentificationCode": "GB"
      }
    },
    "PartyTaxScheme": {
      "RegistrationName": "Bridgtow District Council",
      "CompanyID": "12356478",
      "ExemptionReason": "Local Authority",
      "TaxScheme": {
        "ID": "UK VAT",
        "TaxTypeCode": "VAT"
      }
    },
    "Contact": {
      "Name": "Mr Fred Churchill",
      "Telephone": "0127 2653214",
      "Telefax": "0127 2653215",
      "ElectronicMail": "fred@iytcorporation.gov.uk"
    }
  },
  "BuyerCustomerParty": {
    "Party": {
      "PartyIdentification": {
        "ID": "2203148000007"
      }
    }
  },
  "SellerSupplierParty": {
    "Party": {
      "PartyIdentification": {
        "ID": "6903148000007"
      }
    }
  },
  "ExceptionCriteriaLine": [
    {
      "ID": "exceptionCriteriaLineID",
      "ThresholdValueComparisonCode": "EXCEEDS_EXCEPTION_VALUE",
      "ThresholdQuantity": {
        "value": 120000,
        "unitCode": "KGM"
      },
      "ExceptionStatusCode": "NEW",
      "CollaborationPriorityCode": "HIGH",
      "SupplyChainActivityTypeCode": "SALES",
      "EffectivePeriod": {
        "StartDate": "2010-03-28",
        "EndDate": "2010-08-29"
      },
      "SupplyItem": {
        "Description": "Acme beeswax",
        "Name": "beeswax",
        "BuyersItemIdentification": {
          "ID": "6578489"
        },
        "SellersItemIdentification": {
          "ID": "17589683"
        },
        "StandardItemIdentification": {
          "ID": "00123450000584"
        }
      }
    },
    {
      "ID": "exceptionCriteriaLineID",
      "ThresholdValueComparisonCode": "EXCEEDS_EXCEPTION_VALUE",
      "ThresholdQuantity": {
        "value": 120000,
        "unitCode": "KGM"
      },
      "ExceptionStatusCode": "NEW",
      "CollaborationPriorityCode": "HIGH",
      "PerformanceMetricTypeCode": "SUPPLY",
      "EffectivePeriod": {
        "StartDate": "2010-03-28",
        "EndDate": "2010-05-29"
      },
      "SupplyItem": {
        "StandardItemIdentification": {
          "ID": "00123450000581"
        }
      }
    },
    {
      "ID": "exceptionCriteriaLineID",
      "ThresholdValueComparisonCode": "EXCEEDS_EXCEPTION_VALUE",
      "ThresholdQuantity": {
        "value": 120000,
        "unitCode": "KGM"
      },
      "ExceptionStatusCode": "NEW",
      "CollaborationPriorityCode": "HIGH",
      "EffectivePeriod": {
        "StartDate": "2010-04-28",
        "EndDate": "2010-06-29"
      },
      "SupplyItem": {
        "StandardItemIdentification": {
          "ID": "00123450000582"
        }
      },
      "ForecastExceptionCriterionLine": {
        "ForecastPurposeCode": "SALES_FORECAST",
        "ForecastTypeCode": "BASE",
        "ComparisonDataSourceCode": "SELLER",
        "DataSourceCode": "BUYER",
        "TimeDeltaDaysQuantity": 20
      }
    },
    {
      "ID": "exceptionCriteriaLineID",
      "ThresholdValueComparisonCode": "EXCEEDS_EXCEPTION_VALUE",
      "ThresholdQuantity": {
        "value": 120000,
        "unitCode": "KGM"
      },
      "ExceptionStatusCode": "NEW",
      "CollaborationPriorityCode": "HIGH",
      "EffectivePeriod": {
        "StartDate": "2010-04-28",
        "EndDate": "2010-06-29"
      },
      "SupplyItem": {
        "StandardItemIdentification": {
          "ID": "00123450000580"
        }
      },
      "ForecastExceptionCriterionLine": {
        "ForecastPurposeCode": "SALES_FORECAST",
        "ForecastTypeCode": "BASE",
        "DataSourceCode": "BUYER",
        "TimeDeltaDaysQuantity": 20
      }
    }
  ]
}
