=== kduvekot/ubl-json/zWMqu/json/schemas/maindoc/TransportServiceDescription-2.5.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescription-2",
  "description": "A document sent by a transport service provider to announce the availability of a transport service.",
  "type": "object",
  "properties": {
    "UBLEntity": {
      "const": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescription-2",
      "description": "The JSON Schema identifier for this document type."
    },
    "UBLExtensions": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonExtensionComponents-2#/$defs/UBLExtensionsType"
    },
    "Signature": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/SignatureType"
          }
        }
      ]
    },
    "UBLVersionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UBLVersionID"
    },
    "CustomizationID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CustomizationID"
    },
    "ProfileID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileID"
    },
    "ProfileExecutionID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ProfileExecutionID"
    },
    "ID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ID"
    },
    "CopyIndicator": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/CopyIndicator"
    },
    "UUID": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/UUID"
    },
    "IssueDate": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueDate"
    },
    "IssueTime": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/IssueTime"
    },
    "Note": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/Note"
    },
    "ServiceName": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ServiceName"
    },
    "ResponseCode": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonBasicComponents-2#/$defs/ResponseCode"
    },
    "SenderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ReceiverParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "TransportServiceDescriptionRequestDocumentReference": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/DocumentReferenceType"
    },
    "TransportServiceProviderParty": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PartyType"
    },
    "ServiceChargePaymentTerms": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PaymentTermsType"
    },
    "ValidityPeriod": {
      "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/PeriodType"
    },
    "TransportationService": {
      "oneOf": [
        {
          "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
        },
        {
          "type": "array",
          "items": {
            "$ref": "urn:oasis:names:specification:ubl:schema:json:CommonAggregateComponents-2#/$defs/TransportationServiceType"
          }
        }
      ]
    }
  },
  "required": [
    "UBLEntity",
    "ID"
  ],
  "additionalProperties": false,
  "title": "Transport Service Description. Details"
}

=== kduvekot/ubl-json/gHfrj/json/examples/UBL-TransportServiceDescription-2.1-Example.json
{
  "UBLEntity": "urn:oasis:names:specification:ubl:schema:json:TransportServiceDescription-2",
  "UBLVersionID": "2.1",
  "ID": "TSD_RESP_1",
  "IssueDate": "2011-09-12",
  "IssueTime": "11:01:10+01:00",
  "SenderParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "ReceiverParty": {
    "PartyIdentification": {
      "ID": "4058673827000"
    },
    "PartyName": {
      "Name": "Consignor"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+8687878763",
      "ElectronicMail": "SomeName@consignor.cn"
    }
  },
  "TransportServiceDescriptionRequestDocumentReference": {
    "ID": "TSD_REQ_1"
  },
  "TransportServiceProviderParty": {
    "PartyIdentification": {
      "ID": "4058673827641"
    },
    "PartyName": {
      "Name": "NECOSS"
    },
    "Contact": {
      "Name": "SomeName",
      "Telephone": "+49450557000",
      "ElectronicMail": "SomeName@necoss.de"
    }
  },
  "ServiceChargePaymentTerms": {
    "Amount": {
      "value": 2500,
      "currencyID": "EUR"
    },
    "PaymentDueDate": "2011-11-06"
  },
  "ValidityPeriod": {
    "StartDate": "2011-09-12",
    "EndDate": "2011-09-30",
    "EndTime": "16:00:00+01:00"
  },
  "TransportationService": {
    "TransportServiceCode": "3",
    "SupportedTransportEquipment": [
      {
        "ID": "1",
        "TransportEquipmentTypeCode": "CN",
        "MeasurementDimension": [
          {
            "AttributeID": "Length",
            "Measure": {
              "value": 6.1,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Height",
            "Measure": {
              "value": 2.6,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Width",
            "Measure": {
              "value": 2.44,
              "unitCode": "MTR"
            }
          }
        ]
      },
      {
        "ID": "1",
        "TransportEquipmentTypeCode": "CN",
        "MeasurementDimension": [
          {
            "AttributeID": "Length",
            "Measure": {
              "value": 6.1,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Height",
            "Measure": {
              "value": 2.6,
              "unitCode": "MTR"
            }
          },
          {
            "AttributeID": "Width",
            "Measure": {
              "value": 2.44,
              "unitCode": "MTR"
            }
          }
        ]
      }
    ],
    "ShipmentStage": [
      {
        "ID": "1",
        "PlannedDepartureTransportEvent": {
          "Location": {
            "Address": {
              "ID": "DEHAM",
              "StreetName": "Neuer Wandrahm 4",
              "CityName": "Hamburg",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-03",
            "StartTime": "09:30:10+01:00",
            "EndDate": "2011-10-03",
            "EndTime": "12:30:10+01:00"
          }
        },
        "PlannedArrivalTransportEvent": {
          "Location": {
            "LocationTypeCode": "13",
            "Address": {
              "ID": "4568763527610",
              "StreetName": "Ludwig-Erhard-Str. 15",
              "CityName": "Bremen",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-03",
            "StartTime": "18:30:10+01:00",
            "EndDate": "2011-10-03",
            "EndTime": "21:30:10+01:00"
          }
        }
      },
      {
        "ID": "2",
        "PlannedDepartureTransportEvent": {
          "Location": {
            "LocationTypeCode": "13",
            "Address": {
              "ID": "4568763527610",
              "StreetName": "Ludwig-Erhard-Str. 15",
              "CityName": "Bremen",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-04",
            "StartTime": "09:30:10+01:00",
            "EndDate": "2011-10-04",
            "EndTime": "09:30:10+01:00"
          }
        },
        "PlannedArrivalTransportEvent": {
          "Location": {
            "LocationTypeCode": "13",
            "Address": {
              "StreetName": "Sandstr. 38-40",
              "CityName": "Nurnberg",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-04",
            "StartTime": "15:30:10+01:00",
            "EndDate": "2011-10-04",
            "EndTime": "18:30:10+01:00"
          }
        }
      },
      {
        "ID": "3",
        "PlannedDepartureTransportEvent": {
          "Location": {
            "LocationTypeCode": "13",
            "Address": {
              "StreetName": "Sandstr. 38-40",
              "CityName": "Nurnberg",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-06",
            "StartTime": "09:30:10+01:00",
            "EndDate": "2011-10-06",
            "EndTime": "12:30:10+01:00"
          }
        },
        "PlannedArrivalTransportEvent": {
          "Location": {
            "Address": {
              "StreetName": "Grosse strasse 34",
              "CityName": "Nurnberg",
              "Country": {
                "IdentificationCode": "DE"
              }
            }
          },
          "Period": {
            "StartDate": "2011-10-06",
            "StartTime": "12:30:10+01:00",
            "EndDate": "2011-10-06",
            "EndTime": "15:30:10+01:00"
          }
        }
      }
    ]
  }
}
